/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class lgLcdOpenContext : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal lgLcdOpenContext(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(lgLcdOpenContext obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~lgLcdOpenContext() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LogitechLCDPINVOKE.delete_lgLcdOpenContext(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int connection {
    set {
      LogitechLCDPINVOKE.lgLcdOpenContext_connection_set(swigCPtr, value);
    } 
    get {
      int ret = LogitechLCDPINVOKE.lgLcdOpenContext_connection_get(swigCPtr);
      return ret;
    } 
  }

  public int index {
    set {
      LogitechLCDPINVOKE.lgLcdOpenContext_index_set(swigCPtr, value);
    } 
    get {
      int ret = LogitechLCDPINVOKE.lgLcdOpenContext_index_get(swigCPtr);
      return ret;
    } 
  }

  public lgLcdSoftbuttonsChangedContext onSoftbuttonsChanged {
    set {
      LogitechLCDPINVOKE.lgLcdOpenContext_onSoftbuttonsChanged_set(swigCPtr, lgLcdSoftbuttonsChangedContext.getCPtr(value));
    } 
    get {
      IntPtr cPtr = LogitechLCDPINVOKE.lgLcdOpenContext_onSoftbuttonsChanged_get(swigCPtr);
      lgLcdSoftbuttonsChangedContext ret = (cPtr == IntPtr.Zero) ? null : new lgLcdSoftbuttonsChangedContext(cPtr, false);
      return ret;
    } 
  }

  public int device {
    set {
      LogitechLCDPINVOKE.lgLcdOpenContext_device_set(swigCPtr, value);
    } 
    get {
      int ret = LogitechLCDPINVOKE.lgLcdOpenContext_device_get(swigCPtr);
      return ret;
    } 
  }

  public lgLcdOpenContext() : this(LogitechLCDPINVOKE.new_lgLcdOpenContext(), true) {
  }

}
