/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class lgLcdSoftbuttonsChangedContext : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal lgLcdSoftbuttonsChangedContext(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(lgLcdSoftbuttonsChangedContext obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~lgLcdSoftbuttonsChangedContext() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LogitechLCDPINVOKE.delete_lgLcdSoftbuttonsChangedContext(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_f_int_unsigned_long_q_const__p_void__unsigned_long softbuttonsChangedCallback {
    set {
      LogitechLCDPINVOKE.lgLcdSoftbuttonsChangedContext_softbuttonsChangedCallback_set(swigCPtr, SWIGTYPE_p_f_int_unsigned_long_q_const__p_void__unsigned_long.getCPtr(value));
    } 
    get {
      IntPtr cPtr = LogitechLCDPINVOKE.lgLcdSoftbuttonsChangedContext_softbuttonsChangedCallback_get(swigCPtr);
      SWIGTYPE_p_f_int_unsigned_long_q_const__p_void__unsigned_long ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_f_int_unsigned_long_q_const__p_void__unsigned_long(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_void softbuttonsChangedContext {
    set {
      LogitechLCDPINVOKE.lgLcdSoftbuttonsChangedContext_softbuttonsChangedContext_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      IntPtr cPtr = LogitechLCDPINVOKE.lgLcdSoftbuttonsChangedContext_softbuttonsChangedContext_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public lgLcdSoftbuttonsChangedContext() : this(LogitechLCDPINVOKE.new_lgLcdSoftbuttonsChangedContext(), true) {
  }

}
