/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class lgLcdConnectContextW : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal lgLcdConnectContextW(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(lgLcdConnectContextW obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~lgLcdConnectContextW() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LogitechLCDPINVOKE.delete_lgLcdConnectContextW(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_LPCWSTR appFriendlyName {
    set {
      LogitechLCDPINVOKE.lgLcdConnectContextW_appFriendlyName_set(swigCPtr, SWIGTYPE_p_LPCWSTR.getCPtr(value));
      if (LogitechLCDPINVOKE.SWIGPendingException.Pending) throw LogitechLCDPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_LPCWSTR ret = new SWIGTYPE_p_LPCWSTR(LogitechLCDPINVOKE.lgLcdConnectContextW_appFriendlyName_get(swigCPtr), true);
      if (LogitechLCDPINVOKE.SWIGPendingException.Pending) throw LogitechLCDPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int isPersistent {
    set {
      LogitechLCDPINVOKE.lgLcdConnectContextW_isPersistent_set(swigCPtr, value);
    } 
    get {
      int ret = LogitechLCDPINVOKE.lgLcdConnectContextW_isPersistent_get(swigCPtr);
      return ret;
    } 
  }

  public int isAutostartable {
    set {
      LogitechLCDPINVOKE.lgLcdConnectContextW_isAutostartable_set(swigCPtr, value);
    } 
    get {
      int ret = LogitechLCDPINVOKE.lgLcdConnectContextW_isAutostartable_get(swigCPtr);
      return ret;
    } 
  }

  public lgLcdConfigureContext onConfigure {
    set {
      LogitechLCDPINVOKE.lgLcdConnectContextW_onConfigure_set(swigCPtr, lgLcdConfigureContext.getCPtr(value));
    } 
    get {
      IntPtr cPtr = LogitechLCDPINVOKE.lgLcdConnectContextW_onConfigure_get(swigCPtr);
      lgLcdConfigureContext ret = (cPtr == IntPtr.Zero) ? null : new lgLcdConfigureContext(cPtr, false);
      return ret;
    } 
  }

  public int connection {
    set {
      LogitechLCDPINVOKE.lgLcdConnectContextW_connection_set(swigCPtr, value);
    } 
    get {
      int ret = LogitechLCDPINVOKE.lgLcdConnectContextW_connection_get(swigCPtr);
      return ret;
    } 
  }

  public lgLcdConnectContextW() : this(LogitechLCDPINVOKE.new_lgLcdConnectContextW(), true) {
  }

}
