/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class lgLcdConnectContextExA : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal lgLcdConnectContextExA(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(lgLcdConnectContextExA obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~lgLcdConnectContextExA() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LogitechLCDPINVOKE.delete_lgLcdConnectContextExA(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public string appFriendlyName {
    set {
      LogitechLCDPINVOKE.lgLcdConnectContextExA_appFriendlyName_set(swigCPtr, value);
    } 
    get {
      string ret = LogitechLCDPINVOKE.lgLcdConnectContextExA_appFriendlyName_get(swigCPtr);
      return ret;
    } 
  }

  public int isPersistent {
    set {
      LogitechLCDPINVOKE.lgLcdConnectContextExA_isPersistent_set(swigCPtr, value);
    } 
    get {
      int ret = LogitechLCDPINVOKE.lgLcdConnectContextExA_isPersistent_get(swigCPtr);
      return ret;
    } 
  }

  public int isAutostartable {
    set {
      LogitechLCDPINVOKE.lgLcdConnectContextExA_isAutostartable_set(swigCPtr, value);
    } 
    get {
      int ret = LogitechLCDPINVOKE.lgLcdConnectContextExA_isAutostartable_get(swigCPtr);
      return ret;
    } 
  }

  public lgLcdConfigureContext onConfigure {
    set {
      LogitechLCDPINVOKE.lgLcdConnectContextExA_onConfigure_set(swigCPtr, lgLcdConfigureContext.getCPtr(value));
    } 
    get {
      IntPtr cPtr = LogitechLCDPINVOKE.lgLcdConnectContextExA_onConfigure_get(swigCPtr);
      lgLcdConfigureContext ret = (cPtr == IntPtr.Zero) ? null : new lgLcdConfigureContext(cPtr, false);
      return ret;
    } 
  }

  public int connection {
    set {
      LogitechLCDPINVOKE.lgLcdConnectContextExA_connection_set(swigCPtr, value);
    } 
    get {
      int ret = LogitechLCDPINVOKE.lgLcdConnectContextExA_connection_get(swigCPtr);
      return ret;
    } 
  }

  public uint dwAppletCapabilitiesSupported {
    set {
      LogitechLCDPINVOKE.lgLcdConnectContextExA_dwAppletCapabilitiesSupported_set(swigCPtr, value);
    } 
    get {
      uint ret = LogitechLCDPINVOKE.lgLcdConnectContextExA_dwAppletCapabilitiesSupported_get(swigCPtr);
      return ret;
    } 
  }

  public uint dwReserved1 {
    set {
      LogitechLCDPINVOKE.lgLcdConnectContextExA_dwReserved1_set(swigCPtr, value);
    } 
    get {
      uint ret = LogitechLCDPINVOKE.lgLcdConnectContextExA_dwReserved1_get(swigCPtr);
      return ret;
    } 
  }

  public lgLcdNotificationContext onNotify {
    set {
      LogitechLCDPINVOKE.lgLcdConnectContextExA_onNotify_set(swigCPtr, lgLcdNotificationContext.getCPtr(value));
    } 
    get {
      IntPtr cPtr = LogitechLCDPINVOKE.lgLcdConnectContextExA_onNotify_get(swigCPtr);
      lgLcdNotificationContext ret = (cPtr == IntPtr.Zero) ? null : new lgLcdNotificationContext(cPtr, false);
      return ret;
    } 
  }

  public lgLcdConnectContextExA() : this(LogitechLCDPINVOKE.new_lgLcdConnectContextExA(), true) {
  }

}
