/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class lgLcdBitmapQVGAx32 : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal lgLcdBitmapQVGAx32(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(lgLcdBitmapQVGAx32 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~lgLcdBitmapQVGAx32() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LogitechLCDPINVOKE.delete_lgLcdBitmapQVGAx32(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public lgLcdBitmapHeader hdr {
    set {
      LogitechLCDPINVOKE.lgLcdBitmapQVGAx32_hdr_set(swigCPtr, lgLcdBitmapHeader.getCPtr(value));
    } 
    get {
      IntPtr cPtr = LogitechLCDPINVOKE.lgLcdBitmapQVGAx32_hdr_get(swigCPtr);
      lgLcdBitmapHeader ret = (cPtr == IntPtr.Zero) ? null : new lgLcdBitmapHeader(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_char pixels {
    set {
      LogitechLCDPINVOKE.lgLcdBitmapQVGAx32_pixels_set(swigCPtr, SWIGTYPE_p_unsigned_char.getCPtr(value));
    } 
    get {
      IntPtr cPtr = LogitechLCDPINVOKE.lgLcdBitmapQVGAx32_pixels_get(swigCPtr);
      SWIGTYPE_p_unsigned_char ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
      return ret;
    } 
  }

  public lgLcdBitmapQVGAx32() : this(LogitechLCDPINVOKE.new_lgLcdBitmapQVGAx32(), true) {
  }

}
