/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGCSHARP

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_LogitechLCD(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_LogitechLCD(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_LogitechLCD(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else


/* Includes the header in the wrapper code */
#include "lglcd.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_INVALID_CONNECTION_get() {
  int jresult ;
  int result;
  
  result = (int)((-1));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_INVALID_DEVICE_get() {
  int jresult ;
  int result;
  
  result = (int)((-1));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCDBUTTON_LEFT_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000100));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCDBUTTON_RIGHT_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000200));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCDBUTTON_OK_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000400));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCDBUTTON_CANCEL_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000800));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCDBUTTON_UP_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00001000));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCDBUTTON_DOWN_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00002000));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCDBUTTON_MENU_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00004000));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCDBUTTON_BUTTON0_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000001));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCDBUTTON_BUTTON1_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000002));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCDBUTTON_BUTTON2_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000004));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCDBUTTON_BUTTON3_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000008));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCDBUTTON_BUTTON4_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000010));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCDBUTTON_BUTTON5_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000020));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCDBUTTON_BUTTON6_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000040));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCDBUTTON_BUTTON7_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000080));
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdDeviceDesc_Width_set(void * jarg1, unsigned long jarg2) {
  lgLcdDeviceDesc *arg1 = (lgLcdDeviceDesc *) 0 ;
  DWORD arg2 ;
  
  arg1 = (lgLcdDeviceDesc *)jarg1; 
  arg2 = (DWORD)jarg2; 
  if (arg1) (arg1)->Width = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdDeviceDesc_Width_get(void * jarg1) {
  unsigned long jresult ;
  lgLcdDeviceDesc *arg1 = (lgLcdDeviceDesc *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdDeviceDesc *)jarg1; 
  result = (DWORD) ((arg1)->Width);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdDeviceDesc_Height_set(void * jarg1, unsigned long jarg2) {
  lgLcdDeviceDesc *arg1 = (lgLcdDeviceDesc *) 0 ;
  DWORD arg2 ;
  
  arg1 = (lgLcdDeviceDesc *)jarg1; 
  arg2 = (DWORD)jarg2; 
  if (arg1) (arg1)->Height = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdDeviceDesc_Height_get(void * jarg1) {
  unsigned long jresult ;
  lgLcdDeviceDesc *arg1 = (lgLcdDeviceDesc *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdDeviceDesc *)jarg1; 
  result = (DWORD) ((arg1)->Height);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdDeviceDesc_Bpp_set(void * jarg1, unsigned long jarg2) {
  lgLcdDeviceDesc *arg1 = (lgLcdDeviceDesc *) 0 ;
  DWORD arg2 ;
  
  arg1 = (lgLcdDeviceDesc *)jarg1; 
  arg2 = (DWORD)jarg2; 
  if (arg1) (arg1)->Bpp = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdDeviceDesc_Bpp_get(void * jarg1) {
  unsigned long jresult ;
  lgLcdDeviceDesc *arg1 = (lgLcdDeviceDesc *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdDeviceDesc *)jarg1; 
  result = (DWORD) ((arg1)->Bpp);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdDeviceDesc_NumSoftButtons_set(void * jarg1, unsigned long jarg2) {
  lgLcdDeviceDesc *arg1 = (lgLcdDeviceDesc *) 0 ;
  DWORD arg2 ;
  
  arg1 = (lgLcdDeviceDesc *)jarg1; 
  arg2 = (DWORD)jarg2; 
  if (arg1) (arg1)->NumSoftButtons = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdDeviceDesc_NumSoftButtons_get(void * jarg1) {
  unsigned long jresult ;
  lgLcdDeviceDesc *arg1 = (lgLcdDeviceDesc *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdDeviceDesc *)jarg1; 
  result = (DWORD) ((arg1)->NumSoftButtons);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_lgLcdDeviceDesc() {
  void * jresult ;
  lgLcdDeviceDesc *result = 0 ;
  
  result = (lgLcdDeviceDesc *)calloc(1, sizeof(lgLcdDeviceDesc));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_lgLcdDeviceDesc(void * jarg1) {
  lgLcdDeviceDesc *arg1 = (lgLcdDeviceDesc *) 0 ;
  
  arg1 = (lgLcdDeviceDesc *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdDeviceDescExW_deviceFamilyId_set(void * jarg1, unsigned long jarg2) {
  lgLcdDeviceDescExW *arg1 = (lgLcdDeviceDescExW *) 0 ;
  DWORD arg2 ;
  
  arg1 = (lgLcdDeviceDescExW *)jarg1; 
  arg2 = (DWORD)jarg2; 
  if (arg1) (arg1)->deviceFamilyId = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdDeviceDescExW_deviceFamilyId_get(void * jarg1) {
  unsigned long jresult ;
  lgLcdDeviceDescExW *arg1 = (lgLcdDeviceDescExW *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdDeviceDescExW *)jarg1; 
  result = (DWORD) ((arg1)->deviceFamilyId);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdDeviceDescExW_deviceDisplayName_set(void * jarg1, void * jarg2) {
  lgLcdDeviceDescExW *arg1 = (lgLcdDeviceDescExW *) 0 ;
  WCHAR *arg2 ;
  
  arg1 = (lgLcdDeviceDescExW *)jarg1; 
  arg2 = (WCHAR *)jarg2; 
  {
    size_t ii;
    WCHAR *b = (WCHAR *) arg1->deviceDisplayName;
    for (ii = 0; ii < (size_t)MAX_PATH; ii++) b[ii] = *((WCHAR *) arg2 + ii);
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_lgLcdDeviceDescExW_deviceDisplayName_get(void * jarg1) {
  void * jresult ;
  lgLcdDeviceDescExW *arg1 = (lgLcdDeviceDescExW *) 0 ;
  WCHAR *result = 0 ;
  
  arg1 = (lgLcdDeviceDescExW *)jarg1; 
  result = (WCHAR *)(WCHAR *) ((arg1)->deviceDisplayName);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdDeviceDescExW_Width_set(void * jarg1, unsigned long jarg2) {
  lgLcdDeviceDescExW *arg1 = (lgLcdDeviceDescExW *) 0 ;
  DWORD arg2 ;
  
  arg1 = (lgLcdDeviceDescExW *)jarg1; 
  arg2 = (DWORD)jarg2; 
  if (arg1) (arg1)->Width = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdDeviceDescExW_Width_get(void * jarg1) {
  unsigned long jresult ;
  lgLcdDeviceDescExW *arg1 = (lgLcdDeviceDescExW *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdDeviceDescExW *)jarg1; 
  result = (DWORD) ((arg1)->Width);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdDeviceDescExW_Height_set(void * jarg1, unsigned long jarg2) {
  lgLcdDeviceDescExW *arg1 = (lgLcdDeviceDescExW *) 0 ;
  DWORD arg2 ;
  
  arg1 = (lgLcdDeviceDescExW *)jarg1; 
  arg2 = (DWORD)jarg2; 
  if (arg1) (arg1)->Height = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdDeviceDescExW_Height_get(void * jarg1) {
  unsigned long jresult ;
  lgLcdDeviceDescExW *arg1 = (lgLcdDeviceDescExW *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdDeviceDescExW *)jarg1; 
  result = (DWORD) ((arg1)->Height);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdDeviceDescExW_Bpp_set(void * jarg1, unsigned long jarg2) {
  lgLcdDeviceDescExW *arg1 = (lgLcdDeviceDescExW *) 0 ;
  DWORD arg2 ;
  
  arg1 = (lgLcdDeviceDescExW *)jarg1; 
  arg2 = (DWORD)jarg2; 
  if (arg1) (arg1)->Bpp = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdDeviceDescExW_Bpp_get(void * jarg1) {
  unsigned long jresult ;
  lgLcdDeviceDescExW *arg1 = (lgLcdDeviceDescExW *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdDeviceDescExW *)jarg1; 
  result = (DWORD) ((arg1)->Bpp);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdDeviceDescExW_NumSoftButtons_set(void * jarg1, unsigned long jarg2) {
  lgLcdDeviceDescExW *arg1 = (lgLcdDeviceDescExW *) 0 ;
  DWORD arg2 ;
  
  arg1 = (lgLcdDeviceDescExW *)jarg1; 
  arg2 = (DWORD)jarg2; 
  if (arg1) (arg1)->NumSoftButtons = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdDeviceDescExW_NumSoftButtons_get(void * jarg1) {
  unsigned long jresult ;
  lgLcdDeviceDescExW *arg1 = (lgLcdDeviceDescExW *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdDeviceDescExW *)jarg1; 
  result = (DWORD) ((arg1)->NumSoftButtons);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdDeviceDescExW_Reserved1_set(void * jarg1, unsigned long jarg2) {
  lgLcdDeviceDescExW *arg1 = (lgLcdDeviceDescExW *) 0 ;
  DWORD arg2 ;
  
  arg1 = (lgLcdDeviceDescExW *)jarg1; 
  arg2 = (DWORD)jarg2; 
  if (arg1) (arg1)->Reserved1 = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdDeviceDescExW_Reserved1_get(void * jarg1) {
  unsigned long jresult ;
  lgLcdDeviceDescExW *arg1 = (lgLcdDeviceDescExW *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdDeviceDescExW *)jarg1; 
  result = (DWORD) ((arg1)->Reserved1);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdDeviceDescExW_Reserved2_set(void * jarg1, unsigned long jarg2) {
  lgLcdDeviceDescExW *arg1 = (lgLcdDeviceDescExW *) 0 ;
  DWORD arg2 ;
  
  arg1 = (lgLcdDeviceDescExW *)jarg1; 
  arg2 = (DWORD)jarg2; 
  if (arg1) (arg1)->Reserved2 = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdDeviceDescExW_Reserved2_get(void * jarg1) {
  unsigned long jresult ;
  lgLcdDeviceDescExW *arg1 = (lgLcdDeviceDescExW *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdDeviceDescExW *)jarg1; 
  result = (DWORD) ((arg1)->Reserved2);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_lgLcdDeviceDescExW() {
  void * jresult ;
  lgLcdDeviceDescExW *result = 0 ;
  
  result = (lgLcdDeviceDescExW *)calloc(1, sizeof(lgLcdDeviceDescExW));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_lgLcdDeviceDescExW(void * jarg1) {
  lgLcdDeviceDescExW *arg1 = (lgLcdDeviceDescExW *) 0 ;
  
  arg1 = (lgLcdDeviceDescExW *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdDeviceDescExA_deviceFamilyId_set(void * jarg1, unsigned long jarg2) {
  lgLcdDeviceDescExA *arg1 = (lgLcdDeviceDescExA *) 0 ;
  DWORD arg2 ;
  
  arg1 = (lgLcdDeviceDescExA *)jarg1; 
  arg2 = (DWORD)jarg2; 
  if (arg1) (arg1)->deviceFamilyId = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdDeviceDescExA_deviceFamilyId_get(void * jarg1) {
  unsigned long jresult ;
  lgLcdDeviceDescExA *arg1 = (lgLcdDeviceDescExA *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdDeviceDescExA *)jarg1; 
  result = (DWORD) ((arg1)->deviceFamilyId);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdDeviceDescExA_deviceDisplayName_set(void * jarg1, char * jarg2) {
  lgLcdDeviceDescExA *arg1 = (lgLcdDeviceDescExA *) 0 ;
  CHAR *arg2 ;
  
  arg1 = (lgLcdDeviceDescExA *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    if(arg2) {
      strncpy((char*)arg1->deviceDisplayName, (const char *)arg2, MAX_PATH-1);
      arg1->deviceDisplayName[MAX_PATH-1] = 0;
    } else {
      arg1->deviceDisplayName[0] = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_lgLcdDeviceDescExA_deviceDisplayName_get(void * jarg1) {
  char * jresult ;
  lgLcdDeviceDescExA *arg1 = (lgLcdDeviceDescExA *) 0 ;
  CHAR *result = 0 ;
  
  arg1 = (lgLcdDeviceDescExA *)jarg1; 
  result = (CHAR *)(CHAR *) ((arg1)->deviceDisplayName);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdDeviceDescExA_Width_set(void * jarg1, unsigned long jarg2) {
  lgLcdDeviceDescExA *arg1 = (lgLcdDeviceDescExA *) 0 ;
  DWORD arg2 ;
  
  arg1 = (lgLcdDeviceDescExA *)jarg1; 
  arg2 = (DWORD)jarg2; 
  if (arg1) (arg1)->Width = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdDeviceDescExA_Width_get(void * jarg1) {
  unsigned long jresult ;
  lgLcdDeviceDescExA *arg1 = (lgLcdDeviceDescExA *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdDeviceDescExA *)jarg1; 
  result = (DWORD) ((arg1)->Width);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdDeviceDescExA_Height_set(void * jarg1, unsigned long jarg2) {
  lgLcdDeviceDescExA *arg1 = (lgLcdDeviceDescExA *) 0 ;
  DWORD arg2 ;
  
  arg1 = (lgLcdDeviceDescExA *)jarg1; 
  arg2 = (DWORD)jarg2; 
  if (arg1) (arg1)->Height = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdDeviceDescExA_Height_get(void * jarg1) {
  unsigned long jresult ;
  lgLcdDeviceDescExA *arg1 = (lgLcdDeviceDescExA *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdDeviceDescExA *)jarg1; 
  result = (DWORD) ((arg1)->Height);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdDeviceDescExA_Bpp_set(void * jarg1, unsigned long jarg2) {
  lgLcdDeviceDescExA *arg1 = (lgLcdDeviceDescExA *) 0 ;
  DWORD arg2 ;
  
  arg1 = (lgLcdDeviceDescExA *)jarg1; 
  arg2 = (DWORD)jarg2; 
  if (arg1) (arg1)->Bpp = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdDeviceDescExA_Bpp_get(void * jarg1) {
  unsigned long jresult ;
  lgLcdDeviceDescExA *arg1 = (lgLcdDeviceDescExA *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdDeviceDescExA *)jarg1; 
  result = (DWORD) ((arg1)->Bpp);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdDeviceDescExA_NumSoftButtons_set(void * jarg1, unsigned long jarg2) {
  lgLcdDeviceDescExA *arg1 = (lgLcdDeviceDescExA *) 0 ;
  DWORD arg2 ;
  
  arg1 = (lgLcdDeviceDescExA *)jarg1; 
  arg2 = (DWORD)jarg2; 
  if (arg1) (arg1)->NumSoftButtons = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdDeviceDescExA_NumSoftButtons_get(void * jarg1) {
  unsigned long jresult ;
  lgLcdDeviceDescExA *arg1 = (lgLcdDeviceDescExA *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdDeviceDescExA *)jarg1; 
  result = (DWORD) ((arg1)->NumSoftButtons);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdDeviceDescExA_Reserved1_set(void * jarg1, unsigned long jarg2) {
  lgLcdDeviceDescExA *arg1 = (lgLcdDeviceDescExA *) 0 ;
  DWORD arg2 ;
  
  arg1 = (lgLcdDeviceDescExA *)jarg1; 
  arg2 = (DWORD)jarg2; 
  if (arg1) (arg1)->Reserved1 = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdDeviceDescExA_Reserved1_get(void * jarg1) {
  unsigned long jresult ;
  lgLcdDeviceDescExA *arg1 = (lgLcdDeviceDescExA *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdDeviceDescExA *)jarg1; 
  result = (DWORD) ((arg1)->Reserved1);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdDeviceDescExA_Reserved2_set(void * jarg1, unsigned long jarg2) {
  lgLcdDeviceDescExA *arg1 = (lgLcdDeviceDescExA *) 0 ;
  DWORD arg2 ;
  
  arg1 = (lgLcdDeviceDescExA *)jarg1; 
  arg2 = (DWORD)jarg2; 
  if (arg1) (arg1)->Reserved2 = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdDeviceDescExA_Reserved2_get(void * jarg1) {
  unsigned long jresult ;
  lgLcdDeviceDescExA *arg1 = (lgLcdDeviceDescExA *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdDeviceDescExA *)jarg1; 
  result = (DWORD) ((arg1)->Reserved2);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_lgLcdDeviceDescExA() {
  void * jresult ;
  lgLcdDeviceDescExA *result = 0 ;
  
  result = (lgLcdDeviceDescExA *)calloc(1, sizeof(lgLcdDeviceDescExA));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_lgLcdDeviceDescExA(void * jarg1) {
  lgLcdDeviceDescExA *arg1 = (lgLcdDeviceDescExA *) 0 ;
  
  arg1 = (lgLcdDeviceDescExA *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_BMP_FORMAT_160x43x1_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000001));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_BMP_FORMAT_QVGAx32_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000003));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_BMP_WIDTH_get() {
  int jresult ;
  int result;
  
  result = (int)((160));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_BMP_HEIGHT_get() {
  int jresult ;
  int result;
  
  result = (int)((43));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_BMP_BPP_get() {
  int jresult ;
  int result;
  
  result = (int)((1));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_BW_BMP_WIDTH_get() {
  int jresult ;
  int result;
  
  result = (int)((160));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_BW_BMP_HEIGHT_get() {
  int jresult ;
  int result;
  
  result = (int)((43));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_BW_BMP_BPP_get() {
  int jresult ;
  int result;
  
  result = (int)((1));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_QVGA_BMP_WIDTH_get() {
  int jresult ;
  int result;
  
  result = (int)((320));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_QVGA_BMP_HEIGHT_get() {
  int jresult ;
  int result;
  
  result = (int)((240));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_QVGA_BMP_BPP_get() {
  int jresult ;
  int result;
  
  result = (int)((4));
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdBitmapHeader_Format_set(void * jarg1, unsigned long jarg2) {
  lgLcdBitmapHeader *arg1 = (lgLcdBitmapHeader *) 0 ;
  DWORD arg2 ;
  
  arg1 = (lgLcdBitmapHeader *)jarg1; 
  arg2 = (DWORD)jarg2; 
  if (arg1) (arg1)->Format = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdBitmapHeader_Format_get(void * jarg1) {
  unsigned long jresult ;
  lgLcdBitmapHeader *arg1 = (lgLcdBitmapHeader *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdBitmapHeader *)jarg1; 
  result = (DWORD) ((arg1)->Format);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_lgLcdBitmapHeader() {
  void * jresult ;
  lgLcdBitmapHeader *result = 0 ;
  
  result = (lgLcdBitmapHeader *)calloc(1, sizeof(lgLcdBitmapHeader));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_lgLcdBitmapHeader(void * jarg1) {
  lgLcdBitmapHeader *arg1 = (lgLcdBitmapHeader *) 0 ;
  
  arg1 = (lgLcdBitmapHeader *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdBitmap160x43x1_hdr_set(void * jarg1, void * jarg2) {
  lgLcdBitmap160x43x1 *arg1 = (lgLcdBitmap160x43x1 *) 0 ;
  lgLcdBitmapHeader *arg2 = (lgLcdBitmapHeader *) 0 ;
  
  arg1 = (lgLcdBitmap160x43x1 *)jarg1; 
  arg2 = (lgLcdBitmapHeader *)jarg2; 
  if (arg1) (arg1)->hdr = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_lgLcdBitmap160x43x1_hdr_get(void * jarg1) {
  void * jresult ;
  lgLcdBitmap160x43x1 *arg1 = (lgLcdBitmap160x43x1 *) 0 ;
  lgLcdBitmapHeader *result = 0 ;
  
  arg1 = (lgLcdBitmap160x43x1 *)jarg1; 
  result = (lgLcdBitmapHeader *)& ((arg1)->hdr);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdBitmap160x43x1_pixels_set(void * jarg1, void * jarg2) {
  lgLcdBitmap160x43x1 *arg1 = (lgLcdBitmap160x43x1 *) 0 ;
  BYTE *arg2 ;
  
  arg1 = (lgLcdBitmap160x43x1 *)jarg1; 
  arg2 = (BYTE *)jarg2; 
  {
    size_t ii;
    BYTE *b = (BYTE *) arg1->pixels;
    for (ii = 0; ii < (size_t)(160) *(43) *(1); ii++) b[ii] = *((BYTE *) arg2 + ii);
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_lgLcdBitmap160x43x1_pixels_get(void * jarg1) {
  void * jresult ;
  lgLcdBitmap160x43x1 *arg1 = (lgLcdBitmap160x43x1 *) 0 ;
  BYTE *result = 0 ;
  
  arg1 = (lgLcdBitmap160x43x1 *)jarg1; 
  result = (BYTE *)(BYTE *) ((arg1)->pixels);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_lgLcdBitmap160x43x1() {
  void * jresult ;
  lgLcdBitmap160x43x1 *result = 0 ;
  
  result = (lgLcdBitmap160x43x1 *)calloc(1, sizeof(lgLcdBitmap160x43x1));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_lgLcdBitmap160x43x1(void * jarg1) {
  lgLcdBitmap160x43x1 *arg1 = (lgLcdBitmap160x43x1 *) 0 ;
  
  arg1 = (lgLcdBitmap160x43x1 *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdBitmapQVGAx32_hdr_set(void * jarg1, void * jarg2) {
  lgLcdBitmapQVGAx32 *arg1 = (lgLcdBitmapQVGAx32 *) 0 ;
  lgLcdBitmapHeader *arg2 = (lgLcdBitmapHeader *) 0 ;
  
  arg1 = (lgLcdBitmapQVGAx32 *)jarg1; 
  arg2 = (lgLcdBitmapHeader *)jarg2; 
  if (arg1) (arg1)->hdr = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_lgLcdBitmapQVGAx32_hdr_get(void * jarg1) {
  void * jresult ;
  lgLcdBitmapQVGAx32 *arg1 = (lgLcdBitmapQVGAx32 *) 0 ;
  lgLcdBitmapHeader *result = 0 ;
  
  arg1 = (lgLcdBitmapQVGAx32 *)jarg1; 
  result = (lgLcdBitmapHeader *)& ((arg1)->hdr);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdBitmapQVGAx32_pixels_set(void * jarg1, void * jarg2) {
  lgLcdBitmapQVGAx32 *arg1 = (lgLcdBitmapQVGAx32 *) 0 ;
  BYTE *arg2 ;
  
  arg1 = (lgLcdBitmapQVGAx32 *)jarg1; 
  arg2 = (BYTE *)jarg2; 
  {
    size_t ii;
    BYTE *b = (BYTE *) arg1->pixels;
    for (ii = 0; ii < (size_t)(320) *(240) *(4); ii++) b[ii] = *((BYTE *) arg2 + ii);
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_lgLcdBitmapQVGAx32_pixels_get(void * jarg1) {
  void * jresult ;
  lgLcdBitmapQVGAx32 *arg1 = (lgLcdBitmapQVGAx32 *) 0 ;
  BYTE *result = 0 ;
  
  arg1 = (lgLcdBitmapQVGAx32 *)jarg1; 
  result = (BYTE *)(BYTE *) ((arg1)->pixels);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_lgLcdBitmapQVGAx32() {
  void * jresult ;
  lgLcdBitmapQVGAx32 *result = 0 ;
  
  result = (lgLcdBitmapQVGAx32 *)calloc(1, sizeof(lgLcdBitmapQVGAx32));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_lgLcdBitmapQVGAx32(void * jarg1) {
  lgLcdBitmapQVGAx32 *arg1 = (lgLcdBitmapQVGAx32 *) 0 ;
  
  arg1 = (lgLcdBitmapQVGAx32 *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdBitmap_hdr_set(void * jarg1, void * jarg2) {
  lgLcdBitmap *arg1 = (lgLcdBitmap *) 0 ;
  lgLcdBitmapHeader *arg2 = (lgLcdBitmapHeader *) 0 ;
  
  arg1 = (lgLcdBitmap *)jarg1; 
  arg2 = (lgLcdBitmapHeader *)jarg2; 
  if (arg1) (arg1)->hdr = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_lgLcdBitmap_hdr_get(void * jarg1) {
  void * jresult ;
  lgLcdBitmap *arg1 = (lgLcdBitmap *) 0 ;
  lgLcdBitmapHeader *result = 0 ;
  
  arg1 = (lgLcdBitmap *)jarg1; 
  result = (lgLcdBitmapHeader *)& ((arg1)->hdr);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdBitmap_bmp_mono_set(void * jarg1, void * jarg2) {
  lgLcdBitmap *arg1 = (lgLcdBitmap *) 0 ;
  lgLcdBitmap160x43x1 *arg2 = (lgLcdBitmap160x43x1 *) 0 ;
  
  arg1 = (lgLcdBitmap *)jarg1; 
  arg2 = (lgLcdBitmap160x43x1 *)jarg2; 
  if (arg1) (arg1)->bmp_mono = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_lgLcdBitmap_bmp_mono_get(void * jarg1) {
  void * jresult ;
  lgLcdBitmap *arg1 = (lgLcdBitmap *) 0 ;
  lgLcdBitmap160x43x1 *result = 0 ;
  
  arg1 = (lgLcdBitmap *)jarg1; 
  result = (lgLcdBitmap160x43x1 *)& ((arg1)->bmp_mono);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdBitmap_bmp_qvga32_set(void * jarg1, void * jarg2) {
  lgLcdBitmap *arg1 = (lgLcdBitmap *) 0 ;
  lgLcdBitmapQVGAx32 *arg2 = (lgLcdBitmapQVGAx32 *) 0 ;
  
  arg1 = (lgLcdBitmap *)jarg1; 
  arg2 = (lgLcdBitmapQVGAx32 *)jarg2; 
  if (arg1) (arg1)->bmp_qvga32 = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_lgLcdBitmap_bmp_qvga32_get(void * jarg1) {
  void * jresult ;
  lgLcdBitmap *arg1 = (lgLcdBitmap *) 0 ;
  lgLcdBitmapQVGAx32 *result = 0 ;
  
  arg1 = (lgLcdBitmap *)jarg1; 
  result = (lgLcdBitmapQVGAx32 *)& ((arg1)->bmp_qvga32);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_lgLcdBitmap() {
  void * jresult ;
  lgLcdBitmap *result = 0 ;
  
  result = (lgLcdBitmap *)calloc(1, sizeof(lgLcdBitmap));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_lgLcdBitmap(void * jarg1) {
  lgLcdBitmap *arg1 = (lgLcdBitmap *) 0 ;
  
  arg1 = (lgLcdBitmap *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_PRIORITY_IDLE_NO_SHOW_get() {
  int jresult ;
  int result;
  
  result = (int)((0));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_PRIORITY_BACKGROUND_get() {
  int jresult ;
  int result;
  
  result = (int)((64));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_PRIORITY_NORMAL_get() {
  int jresult ;
  int result;
  
  result = (int)((128));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_PRIORITY_ALERT_get() {
  int jresult ;
  int result;
  
  result = (int)((255));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_LCD_FOREGROUND_APP_NO_get() {
  int jresult ;
  int result;
  
  result = (int)((0));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_LCD_FOREGROUND_APP_YES_get() {
  int jresult ;
  int result;
  
  result = (int)((1));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_DEVICE_FAMILY_BW_160x43_GAMING_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000001));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_DEVICE_FAMILY_KEYBOARD_G15_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000001));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_DEVICE_FAMILY_BW_160x43_AUDIO_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000002));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_DEVICE_FAMILY_SPEAKERS_Z10_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000002));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_DEVICE_FAMILY_JACKBOX_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000004));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_DEVICE_FAMILY_BW_160x43_BASIC_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000008));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_DEVICE_FAMILY_LCDEMULATOR_G15_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000008));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_DEVICE_FAMILY_RAINBOW_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000010));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_DEVICE_FAMILY_QVGA_BASIC_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000020));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_DEVICE_FAMILY_QVGA_GAMING_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000040));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_DEVICE_FAMILY_GAMEBOARD_G13_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000080));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_DEVICE_FAMILY_KEYBOARD_G510_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000100));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_DEVICE_FAMILY_OTHER_get() {
  int jresult ;
  int result;
  
  result = (int)((0x80000000));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_DEVICE_FAMILY_ALL_BW_160x43_get() {
  int jresult ;
  int result;
  
  result = (int)(((0x00000001)|(0x00000002)|(0x00000004)|(0x00000008)|(0x00000010)|(0x00000080)|(0x00000100)));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_DEVICE_FAMILY_ALL_QVGA_get() {
  int jresult ;
  int result;
  
  result = (int)(((0x00000020)|(0x00000040)));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_DEVICE_FAMILY_ALL_get() {
  int jresult ;
  int result;
  
  result = (int)((((0x00000001)|(0x00000002)|(0x00000004)|(0x00000008)|(0x00000010)|(0x00000080)|(0x00000100))|((0x00000020)|(0x00000040))));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_APPLET_CAP_BASIC_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000000));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_APPLET_CAP_BW_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000001));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_APPLET_CAP_QVGA_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000002));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_NOTIFICATION_DEVICE_ARRIVAL_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000001));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_NOTIFICATION_DEVICE_REMOVAL_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000002));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_NOTIFICATION_CLOSE_CONNECTION_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000003));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_NOTIFICATION_APPLET_DISABLED_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000004));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_NOTIFICATION_APPLET_ENABLED_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000005));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_NOTIFICATION_TERMINATE_APPLET_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000006));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_DEVICE_BW_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000001));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_LGLCD_DEVICE_QVGA_get() {
  int jresult ;
  int result;
  
  result = (int)((0x00000002));
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConfigureContext_configCallback_set(void * jarg1, void * jarg2) {
  lgLcdConfigureContext *arg1 = (lgLcdConfigureContext *) 0 ;
  lgLcdOnConfigureCB arg2 = (lgLcdOnConfigureCB) 0 ;
  
  arg1 = (lgLcdConfigureContext *)jarg1; 
  arg2 = (lgLcdOnConfigureCB)jarg2; 
  if (arg1) (arg1)->configCallback = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_lgLcdConfigureContext_configCallback_get(void * jarg1) {
  void * jresult ;
  lgLcdConfigureContext *arg1 = (lgLcdConfigureContext *) 0 ;
  lgLcdOnConfigureCB result;
  
  arg1 = (lgLcdConfigureContext *)jarg1; 
  result = (lgLcdOnConfigureCB) ((arg1)->configCallback);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConfigureContext_configContext_set(void * jarg1, void * jarg2) {
  lgLcdConfigureContext *arg1 = (lgLcdConfigureContext *) 0 ;
  PVOID arg2 = (PVOID) 0 ;
  
  arg1 = (lgLcdConfigureContext *)jarg1; 
  arg2 = (PVOID)jarg2; 
  if (arg1) (arg1)->configContext = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_lgLcdConfigureContext_configContext_get(void * jarg1) {
  void * jresult ;
  lgLcdConfigureContext *arg1 = (lgLcdConfigureContext *) 0 ;
  PVOID result;
  
  arg1 = (lgLcdConfigureContext *)jarg1; 
  result = (PVOID) ((arg1)->configContext);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_lgLcdConfigureContext() {
  void * jresult ;
  lgLcdConfigureContext *result = 0 ;
  
  result = (lgLcdConfigureContext *)calloc(1, sizeof(lgLcdConfigureContext));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_lgLcdConfigureContext(void * jarg1) {
  lgLcdConfigureContext *arg1 = (lgLcdConfigureContext *) 0 ;
  
  arg1 = (lgLcdConfigureContext *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdNotificationContext_notificationCallback_set(void * jarg1, void * jarg2) {
  lgLcdNotificationContext *arg1 = (lgLcdNotificationContext *) 0 ;
  lgLcdOnNotificationCB arg2 = (lgLcdOnNotificationCB) 0 ;
  
  arg1 = (lgLcdNotificationContext *)jarg1; 
  arg2 = (lgLcdOnNotificationCB)jarg2; 
  if (arg1) (arg1)->notificationCallback = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_lgLcdNotificationContext_notificationCallback_get(void * jarg1) {
  void * jresult ;
  lgLcdNotificationContext *arg1 = (lgLcdNotificationContext *) 0 ;
  lgLcdOnNotificationCB result;
  
  arg1 = (lgLcdNotificationContext *)jarg1; 
  result = (lgLcdOnNotificationCB) ((arg1)->notificationCallback);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdNotificationContext_notifyContext_set(void * jarg1, void * jarg2) {
  lgLcdNotificationContext *arg1 = (lgLcdNotificationContext *) 0 ;
  PVOID arg2 = (PVOID) 0 ;
  
  arg1 = (lgLcdNotificationContext *)jarg1; 
  arg2 = (PVOID)jarg2; 
  if (arg1) (arg1)->notifyContext = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_lgLcdNotificationContext_notifyContext_get(void * jarg1) {
  void * jresult ;
  lgLcdNotificationContext *arg1 = (lgLcdNotificationContext *) 0 ;
  PVOID result;
  
  arg1 = (lgLcdNotificationContext *)jarg1; 
  result = (PVOID) ((arg1)->notifyContext);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_lgLcdNotificationContext() {
  void * jresult ;
  lgLcdNotificationContext *result = 0 ;
  
  result = (lgLcdNotificationContext *)calloc(1, sizeof(lgLcdNotificationContext));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_lgLcdNotificationContext(void * jarg1) {
  lgLcdNotificationContext *arg1 = (lgLcdNotificationContext *) 0 ;
  
  arg1 = (lgLcdNotificationContext *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConnectContextW_appFriendlyName_set(void * jarg1, void * jarg2) {
  lgLcdConnectContextW *arg1 = (lgLcdConnectContextW *) 0 ;
  LPCWSTR arg2 ;
  LPCWSTR *argp2 ;
  
  arg1 = (lgLcdConnectContextW *)jarg1; 
  argp2 = (LPCWSTR *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null LPCWSTR", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->appFriendlyName = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_lgLcdConnectContextW_appFriendlyName_get(void * jarg1) {
  void * jresult ;
  lgLcdConnectContextW *arg1 = (lgLcdConnectContextW *) 0 ;
  LPCWSTR result;
  
  arg1 = (lgLcdConnectContextW *)jarg1; 
  result =  ((arg1)->appFriendlyName);
  {
    LPCWSTR * resultptr = (LPCWSTR *) malloc(sizeof(LPCWSTR));
    memmove(resultptr, &result, sizeof(LPCWSTR));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConnectContextW_isPersistent_set(void * jarg1, int jarg2) {
  lgLcdConnectContextW *arg1 = (lgLcdConnectContextW *) 0 ;
  BOOL arg2 ;
  
  arg1 = (lgLcdConnectContextW *)jarg1; 
  arg2 = (BOOL)jarg2; 
  if (arg1) (arg1)->isPersistent = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_lgLcdConnectContextW_isPersistent_get(void * jarg1) {
  int jresult ;
  lgLcdConnectContextW *arg1 = (lgLcdConnectContextW *) 0 ;
  BOOL result;
  
  arg1 = (lgLcdConnectContextW *)jarg1; 
  result = (BOOL) ((arg1)->isPersistent);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConnectContextW_isAutostartable_set(void * jarg1, int jarg2) {
  lgLcdConnectContextW *arg1 = (lgLcdConnectContextW *) 0 ;
  BOOL arg2 ;
  
  arg1 = (lgLcdConnectContextW *)jarg1; 
  arg2 = (BOOL)jarg2; 
  if (arg1) (arg1)->isAutostartable = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_lgLcdConnectContextW_isAutostartable_get(void * jarg1) {
  int jresult ;
  lgLcdConnectContextW *arg1 = (lgLcdConnectContextW *) 0 ;
  BOOL result;
  
  arg1 = (lgLcdConnectContextW *)jarg1; 
  result = (BOOL) ((arg1)->isAutostartable);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConnectContextW_onConfigure_set(void * jarg1, void * jarg2) {
  lgLcdConnectContextW *arg1 = (lgLcdConnectContextW *) 0 ;
  lgLcdConfigureContext *arg2 = (lgLcdConfigureContext *) 0 ;
  
  arg1 = (lgLcdConnectContextW *)jarg1; 
  arg2 = (lgLcdConfigureContext *)jarg2; 
  if (arg1) (arg1)->onConfigure = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_lgLcdConnectContextW_onConfigure_get(void * jarg1) {
  void * jresult ;
  lgLcdConnectContextW *arg1 = (lgLcdConnectContextW *) 0 ;
  lgLcdConfigureContext *result = 0 ;
  
  arg1 = (lgLcdConnectContextW *)jarg1; 
  result = (lgLcdConfigureContext *)& ((arg1)->onConfigure);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConnectContextW_connection_set(void * jarg1, int jarg2) {
  lgLcdConnectContextW *arg1 = (lgLcdConnectContextW *) 0 ;
  int arg2 ;
  
  arg1 = (lgLcdConnectContextW *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->connection = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_lgLcdConnectContextW_connection_get(void * jarg1) {
  int jresult ;
  lgLcdConnectContextW *arg1 = (lgLcdConnectContextW *) 0 ;
  int result;
  
  arg1 = (lgLcdConnectContextW *)jarg1; 
  result = (int) ((arg1)->connection);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_lgLcdConnectContextW() {
  void * jresult ;
  lgLcdConnectContextW *result = 0 ;
  
  result = (lgLcdConnectContextW *)calloc(1, sizeof(lgLcdConnectContextW));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_lgLcdConnectContextW(void * jarg1) {
  lgLcdConnectContextW *arg1 = (lgLcdConnectContextW *) 0 ;
  
  arg1 = (lgLcdConnectContextW *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConnectContextA_appFriendlyName_set(void * jarg1, char * jarg2) {
  lgLcdConnectContextA *arg1 = (lgLcdConnectContextA *) 0 ;
  LPCSTR arg2 = (LPCSTR) 0 ;
  
  arg1 = (lgLcdConnectContextA *)jarg1; 
  arg2 = (LPCSTR)jarg2; 
  {
    if (arg2) {
      arg1->appFriendlyName = (LPCSTR) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->appFriendlyName, (const char *)arg2);
    } else {
      arg1->appFriendlyName = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_lgLcdConnectContextA_appFriendlyName_get(void * jarg1) {
  char * jresult ;
  lgLcdConnectContextA *arg1 = (lgLcdConnectContextA *) 0 ;
  LPCSTR result;
  
  arg1 = (lgLcdConnectContextA *)jarg1; 
  result = (LPCSTR) ((arg1)->appFriendlyName);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConnectContextA_isPersistent_set(void * jarg1, int jarg2) {
  lgLcdConnectContextA *arg1 = (lgLcdConnectContextA *) 0 ;
  BOOL arg2 ;
  
  arg1 = (lgLcdConnectContextA *)jarg1; 
  arg2 = (BOOL)jarg2; 
  if (arg1) (arg1)->isPersistent = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_lgLcdConnectContextA_isPersistent_get(void * jarg1) {
  int jresult ;
  lgLcdConnectContextA *arg1 = (lgLcdConnectContextA *) 0 ;
  BOOL result;
  
  arg1 = (lgLcdConnectContextA *)jarg1; 
  result = (BOOL) ((arg1)->isPersistent);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConnectContextA_isAutostartable_set(void * jarg1, int jarg2) {
  lgLcdConnectContextA *arg1 = (lgLcdConnectContextA *) 0 ;
  BOOL arg2 ;
  
  arg1 = (lgLcdConnectContextA *)jarg1; 
  arg2 = (BOOL)jarg2; 
  if (arg1) (arg1)->isAutostartable = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_lgLcdConnectContextA_isAutostartable_get(void * jarg1) {
  int jresult ;
  lgLcdConnectContextA *arg1 = (lgLcdConnectContextA *) 0 ;
  BOOL result;
  
  arg1 = (lgLcdConnectContextA *)jarg1; 
  result = (BOOL) ((arg1)->isAutostartable);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConnectContextA_onConfigure_set(void * jarg1, void * jarg2) {
  lgLcdConnectContextA *arg1 = (lgLcdConnectContextA *) 0 ;
  lgLcdConfigureContext *arg2 = (lgLcdConfigureContext *) 0 ;
  
  arg1 = (lgLcdConnectContextA *)jarg1; 
  arg2 = (lgLcdConfigureContext *)jarg2; 
  if (arg1) (arg1)->onConfigure = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_lgLcdConnectContextA_onConfigure_get(void * jarg1) {
  void * jresult ;
  lgLcdConnectContextA *arg1 = (lgLcdConnectContextA *) 0 ;
  lgLcdConfigureContext *result = 0 ;
  
  arg1 = (lgLcdConnectContextA *)jarg1; 
  result = (lgLcdConfigureContext *)& ((arg1)->onConfigure);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConnectContextA_connection_set(void * jarg1, int jarg2) {
  lgLcdConnectContextA *arg1 = (lgLcdConnectContextA *) 0 ;
  int arg2 ;
  
  arg1 = (lgLcdConnectContextA *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->connection = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_lgLcdConnectContextA_connection_get(void * jarg1) {
  int jresult ;
  lgLcdConnectContextA *arg1 = (lgLcdConnectContextA *) 0 ;
  int result;
  
  arg1 = (lgLcdConnectContextA *)jarg1; 
  result = (int) ((arg1)->connection);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_lgLcdConnectContextA() {
  void * jresult ;
  lgLcdConnectContextA *result = 0 ;
  
  result = (lgLcdConnectContextA *)calloc(1, sizeof(lgLcdConnectContextA));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_lgLcdConnectContextA(void * jarg1) {
  lgLcdConnectContextA *arg1 = (lgLcdConnectContextA *) 0 ;
  
  arg1 = (lgLcdConnectContextA *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConnectContextExW_appFriendlyName_set(void * jarg1, void * jarg2) {
  lgLcdConnectContextExW *arg1 = (lgLcdConnectContextExW *) 0 ;
  LPCWSTR arg2 ;
  LPCWSTR *argp2 ;
  
  arg1 = (lgLcdConnectContextExW *)jarg1; 
  argp2 = (LPCWSTR *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null LPCWSTR", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->appFriendlyName = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_lgLcdConnectContextExW_appFriendlyName_get(void * jarg1) {
  void * jresult ;
  lgLcdConnectContextExW *arg1 = (lgLcdConnectContextExW *) 0 ;
  LPCWSTR result;
  
  arg1 = (lgLcdConnectContextExW *)jarg1; 
  result =  ((arg1)->appFriendlyName);
  {
    LPCWSTR * resultptr = (LPCWSTR *) malloc(sizeof(LPCWSTR));
    memmove(resultptr, &result, sizeof(LPCWSTR));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConnectContextExW_isPersistent_set(void * jarg1, int jarg2) {
  lgLcdConnectContextExW *arg1 = (lgLcdConnectContextExW *) 0 ;
  BOOL arg2 ;
  
  arg1 = (lgLcdConnectContextExW *)jarg1; 
  arg2 = (BOOL)jarg2; 
  if (arg1) (arg1)->isPersistent = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_lgLcdConnectContextExW_isPersistent_get(void * jarg1) {
  int jresult ;
  lgLcdConnectContextExW *arg1 = (lgLcdConnectContextExW *) 0 ;
  BOOL result;
  
  arg1 = (lgLcdConnectContextExW *)jarg1; 
  result = (BOOL) ((arg1)->isPersistent);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConnectContextExW_isAutostartable_set(void * jarg1, int jarg2) {
  lgLcdConnectContextExW *arg1 = (lgLcdConnectContextExW *) 0 ;
  BOOL arg2 ;
  
  arg1 = (lgLcdConnectContextExW *)jarg1; 
  arg2 = (BOOL)jarg2; 
  if (arg1) (arg1)->isAutostartable = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_lgLcdConnectContextExW_isAutostartable_get(void * jarg1) {
  int jresult ;
  lgLcdConnectContextExW *arg1 = (lgLcdConnectContextExW *) 0 ;
  BOOL result;
  
  arg1 = (lgLcdConnectContextExW *)jarg1; 
  result = (BOOL) ((arg1)->isAutostartable);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConnectContextExW_onConfigure_set(void * jarg1, void * jarg2) {
  lgLcdConnectContextExW *arg1 = (lgLcdConnectContextExW *) 0 ;
  lgLcdConfigureContext *arg2 = (lgLcdConfigureContext *) 0 ;
  
  arg1 = (lgLcdConnectContextExW *)jarg1; 
  arg2 = (lgLcdConfigureContext *)jarg2; 
  if (arg1) (arg1)->onConfigure = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_lgLcdConnectContextExW_onConfigure_get(void * jarg1) {
  void * jresult ;
  lgLcdConnectContextExW *arg1 = (lgLcdConnectContextExW *) 0 ;
  lgLcdConfigureContext *result = 0 ;
  
  arg1 = (lgLcdConnectContextExW *)jarg1; 
  result = (lgLcdConfigureContext *)& ((arg1)->onConfigure);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConnectContextExW_connection_set(void * jarg1, int jarg2) {
  lgLcdConnectContextExW *arg1 = (lgLcdConnectContextExW *) 0 ;
  int arg2 ;
  
  arg1 = (lgLcdConnectContextExW *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->connection = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_lgLcdConnectContextExW_connection_get(void * jarg1) {
  int jresult ;
  lgLcdConnectContextExW *arg1 = (lgLcdConnectContextExW *) 0 ;
  int result;
  
  arg1 = (lgLcdConnectContextExW *)jarg1; 
  result = (int) ((arg1)->connection);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConnectContextExW_dwAppletCapabilitiesSupported_set(void * jarg1, unsigned long jarg2) {
  lgLcdConnectContextExW *arg1 = (lgLcdConnectContextExW *) 0 ;
  DWORD arg2 ;
  
  arg1 = (lgLcdConnectContextExW *)jarg1; 
  arg2 = (DWORD)jarg2; 
  if (arg1) (arg1)->dwAppletCapabilitiesSupported = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdConnectContextExW_dwAppletCapabilitiesSupported_get(void * jarg1) {
  unsigned long jresult ;
  lgLcdConnectContextExW *arg1 = (lgLcdConnectContextExW *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdConnectContextExW *)jarg1; 
  result = (DWORD) ((arg1)->dwAppletCapabilitiesSupported);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConnectContextExW_dwReserved1_set(void * jarg1, unsigned long jarg2) {
  lgLcdConnectContextExW *arg1 = (lgLcdConnectContextExW *) 0 ;
  DWORD arg2 ;
  
  arg1 = (lgLcdConnectContextExW *)jarg1; 
  arg2 = (DWORD)jarg2; 
  if (arg1) (arg1)->dwReserved1 = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdConnectContextExW_dwReserved1_get(void * jarg1) {
  unsigned long jresult ;
  lgLcdConnectContextExW *arg1 = (lgLcdConnectContextExW *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdConnectContextExW *)jarg1; 
  result = (DWORD) ((arg1)->dwReserved1);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConnectContextExW_onNotify_set(void * jarg1, void * jarg2) {
  lgLcdConnectContextExW *arg1 = (lgLcdConnectContextExW *) 0 ;
  lgLcdNotificationContext *arg2 = (lgLcdNotificationContext *) 0 ;
  
  arg1 = (lgLcdConnectContextExW *)jarg1; 
  arg2 = (lgLcdNotificationContext *)jarg2; 
  if (arg1) (arg1)->onNotify = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_lgLcdConnectContextExW_onNotify_get(void * jarg1) {
  void * jresult ;
  lgLcdConnectContextExW *arg1 = (lgLcdConnectContextExW *) 0 ;
  lgLcdNotificationContext *result = 0 ;
  
  arg1 = (lgLcdConnectContextExW *)jarg1; 
  result = (lgLcdNotificationContext *)& ((arg1)->onNotify);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_lgLcdConnectContextExW() {
  void * jresult ;
  lgLcdConnectContextExW *result = 0 ;
  
  result = (lgLcdConnectContextExW *)calloc(1, sizeof(lgLcdConnectContextExW));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_lgLcdConnectContextExW(void * jarg1) {
  lgLcdConnectContextExW *arg1 = (lgLcdConnectContextExW *) 0 ;
  
  arg1 = (lgLcdConnectContextExW *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConnectContextExA_appFriendlyName_set(void * jarg1, char * jarg2) {
  lgLcdConnectContextExA *arg1 = (lgLcdConnectContextExA *) 0 ;
  LPCSTR arg2 = (LPCSTR) 0 ;
  
  arg1 = (lgLcdConnectContextExA *)jarg1; 
  arg2 = (LPCSTR)jarg2; 
  {
    if (arg2) {
      arg1->appFriendlyName = (LPCSTR) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->appFriendlyName, (const char *)arg2);
    } else {
      arg1->appFriendlyName = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_lgLcdConnectContextExA_appFriendlyName_get(void * jarg1) {
  char * jresult ;
  lgLcdConnectContextExA *arg1 = (lgLcdConnectContextExA *) 0 ;
  LPCSTR result;
  
  arg1 = (lgLcdConnectContextExA *)jarg1; 
  result = (LPCSTR) ((arg1)->appFriendlyName);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConnectContextExA_isPersistent_set(void * jarg1, int jarg2) {
  lgLcdConnectContextExA *arg1 = (lgLcdConnectContextExA *) 0 ;
  BOOL arg2 ;
  
  arg1 = (lgLcdConnectContextExA *)jarg1; 
  arg2 = (BOOL)jarg2; 
  if (arg1) (arg1)->isPersistent = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_lgLcdConnectContextExA_isPersistent_get(void * jarg1) {
  int jresult ;
  lgLcdConnectContextExA *arg1 = (lgLcdConnectContextExA *) 0 ;
  BOOL result;
  
  arg1 = (lgLcdConnectContextExA *)jarg1; 
  result = (BOOL) ((arg1)->isPersistent);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConnectContextExA_isAutostartable_set(void * jarg1, int jarg2) {
  lgLcdConnectContextExA *arg1 = (lgLcdConnectContextExA *) 0 ;
  BOOL arg2 ;
  
  arg1 = (lgLcdConnectContextExA *)jarg1; 
  arg2 = (BOOL)jarg2; 
  if (arg1) (arg1)->isAutostartable = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_lgLcdConnectContextExA_isAutostartable_get(void * jarg1) {
  int jresult ;
  lgLcdConnectContextExA *arg1 = (lgLcdConnectContextExA *) 0 ;
  BOOL result;
  
  arg1 = (lgLcdConnectContextExA *)jarg1; 
  result = (BOOL) ((arg1)->isAutostartable);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConnectContextExA_onConfigure_set(void * jarg1, void * jarg2) {
  lgLcdConnectContextExA *arg1 = (lgLcdConnectContextExA *) 0 ;
  lgLcdConfigureContext *arg2 = (lgLcdConfigureContext *) 0 ;
  
  arg1 = (lgLcdConnectContextExA *)jarg1; 
  arg2 = (lgLcdConfigureContext *)jarg2; 
  if (arg1) (arg1)->onConfigure = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_lgLcdConnectContextExA_onConfigure_get(void * jarg1) {
  void * jresult ;
  lgLcdConnectContextExA *arg1 = (lgLcdConnectContextExA *) 0 ;
  lgLcdConfigureContext *result = 0 ;
  
  arg1 = (lgLcdConnectContextExA *)jarg1; 
  result = (lgLcdConfigureContext *)& ((arg1)->onConfigure);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConnectContextExA_connection_set(void * jarg1, int jarg2) {
  lgLcdConnectContextExA *arg1 = (lgLcdConnectContextExA *) 0 ;
  int arg2 ;
  
  arg1 = (lgLcdConnectContextExA *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->connection = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_lgLcdConnectContextExA_connection_get(void * jarg1) {
  int jresult ;
  lgLcdConnectContextExA *arg1 = (lgLcdConnectContextExA *) 0 ;
  int result;
  
  arg1 = (lgLcdConnectContextExA *)jarg1; 
  result = (int) ((arg1)->connection);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConnectContextExA_dwAppletCapabilitiesSupported_set(void * jarg1, unsigned long jarg2) {
  lgLcdConnectContextExA *arg1 = (lgLcdConnectContextExA *) 0 ;
  DWORD arg2 ;
  
  arg1 = (lgLcdConnectContextExA *)jarg1; 
  arg2 = (DWORD)jarg2; 
  if (arg1) (arg1)->dwAppletCapabilitiesSupported = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdConnectContextExA_dwAppletCapabilitiesSupported_get(void * jarg1) {
  unsigned long jresult ;
  lgLcdConnectContextExA *arg1 = (lgLcdConnectContextExA *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdConnectContextExA *)jarg1; 
  result = (DWORD) ((arg1)->dwAppletCapabilitiesSupported);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConnectContextExA_dwReserved1_set(void * jarg1, unsigned long jarg2) {
  lgLcdConnectContextExA *arg1 = (lgLcdConnectContextExA *) 0 ;
  DWORD arg2 ;
  
  arg1 = (lgLcdConnectContextExA *)jarg1; 
  arg2 = (DWORD)jarg2; 
  if (arg1) (arg1)->dwReserved1 = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdConnectContextExA_dwReserved1_get(void * jarg1) {
  unsigned long jresult ;
  lgLcdConnectContextExA *arg1 = (lgLcdConnectContextExA *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdConnectContextExA *)jarg1; 
  result = (DWORD) ((arg1)->dwReserved1);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdConnectContextExA_onNotify_set(void * jarg1, void * jarg2) {
  lgLcdConnectContextExA *arg1 = (lgLcdConnectContextExA *) 0 ;
  lgLcdNotificationContext *arg2 = (lgLcdNotificationContext *) 0 ;
  
  arg1 = (lgLcdConnectContextExA *)jarg1; 
  arg2 = (lgLcdNotificationContext *)jarg2; 
  if (arg1) (arg1)->onNotify = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_lgLcdConnectContextExA_onNotify_get(void * jarg1) {
  void * jresult ;
  lgLcdConnectContextExA *arg1 = (lgLcdConnectContextExA *) 0 ;
  lgLcdNotificationContext *result = 0 ;
  
  arg1 = (lgLcdConnectContextExA *)jarg1; 
  result = (lgLcdNotificationContext *)& ((arg1)->onNotify);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_lgLcdConnectContextExA() {
  void * jresult ;
  lgLcdConnectContextExA *result = 0 ;
  
  result = (lgLcdConnectContextExA *)calloc(1, sizeof(lgLcdConnectContextExA));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_lgLcdConnectContextExA(void * jarg1) {
  lgLcdConnectContextExA *arg1 = (lgLcdConnectContextExA *) 0 ;
  
  arg1 = (lgLcdConnectContextExA *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdSoftbuttonsChangedContext_softbuttonsChangedCallback_set(void * jarg1, void * jarg2) {
  lgLcdSoftbuttonsChangedContext *arg1 = (lgLcdSoftbuttonsChangedContext *) 0 ;
  lgLcdOnSoftButtonsCB arg2 = (lgLcdOnSoftButtonsCB) 0 ;
  
  arg1 = (lgLcdSoftbuttonsChangedContext *)jarg1; 
  arg2 = (lgLcdOnSoftButtonsCB)jarg2; 
  if (arg1) (arg1)->softbuttonsChangedCallback = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_lgLcdSoftbuttonsChangedContext_softbuttonsChangedCallback_get(void * jarg1) {
  void * jresult ;
  lgLcdSoftbuttonsChangedContext *arg1 = (lgLcdSoftbuttonsChangedContext *) 0 ;
  lgLcdOnSoftButtonsCB result;
  
  arg1 = (lgLcdSoftbuttonsChangedContext *)jarg1; 
  result = (lgLcdOnSoftButtonsCB) ((arg1)->softbuttonsChangedCallback);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdSoftbuttonsChangedContext_softbuttonsChangedContext_set(void * jarg1, void * jarg2) {
  lgLcdSoftbuttonsChangedContext *arg1 = (lgLcdSoftbuttonsChangedContext *) 0 ;
  PVOID arg2 = (PVOID) 0 ;
  
  arg1 = (lgLcdSoftbuttonsChangedContext *)jarg1; 
  arg2 = (PVOID)jarg2; 
  if (arg1) (arg1)->softbuttonsChangedContext = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_lgLcdSoftbuttonsChangedContext_softbuttonsChangedContext_get(void * jarg1) {
  void * jresult ;
  lgLcdSoftbuttonsChangedContext *arg1 = (lgLcdSoftbuttonsChangedContext *) 0 ;
  PVOID result;
  
  arg1 = (lgLcdSoftbuttonsChangedContext *)jarg1; 
  result = (PVOID) ((arg1)->softbuttonsChangedContext);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_lgLcdSoftbuttonsChangedContext() {
  void * jresult ;
  lgLcdSoftbuttonsChangedContext *result = 0 ;
  
  result = (lgLcdSoftbuttonsChangedContext *)calloc(1, sizeof(lgLcdSoftbuttonsChangedContext));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_lgLcdSoftbuttonsChangedContext(void * jarg1) {
  lgLcdSoftbuttonsChangedContext *arg1 = (lgLcdSoftbuttonsChangedContext *) 0 ;
  
  arg1 = (lgLcdSoftbuttonsChangedContext *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdOpenContext_connection_set(void * jarg1, int jarg2) {
  lgLcdOpenContext *arg1 = (lgLcdOpenContext *) 0 ;
  int arg2 ;
  
  arg1 = (lgLcdOpenContext *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->connection = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_lgLcdOpenContext_connection_get(void * jarg1) {
  int jresult ;
  lgLcdOpenContext *arg1 = (lgLcdOpenContext *) 0 ;
  int result;
  
  arg1 = (lgLcdOpenContext *)jarg1; 
  result = (int) ((arg1)->connection);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdOpenContext_index_set(void * jarg1, int jarg2) {
  lgLcdOpenContext *arg1 = (lgLcdOpenContext *) 0 ;
  int arg2 ;
  
  arg1 = (lgLcdOpenContext *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->index = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_lgLcdOpenContext_index_get(void * jarg1) {
  int jresult ;
  lgLcdOpenContext *arg1 = (lgLcdOpenContext *) 0 ;
  int result;
  
  arg1 = (lgLcdOpenContext *)jarg1; 
  result = (int) ((arg1)->index);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdOpenContext_onSoftbuttonsChanged_set(void * jarg1, void * jarg2) {
  lgLcdOpenContext *arg1 = (lgLcdOpenContext *) 0 ;
  lgLcdSoftbuttonsChangedContext *arg2 = (lgLcdSoftbuttonsChangedContext *) 0 ;
  
  arg1 = (lgLcdOpenContext *)jarg1; 
  arg2 = (lgLcdSoftbuttonsChangedContext *)jarg2; 
  if (arg1) (arg1)->onSoftbuttonsChanged = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_lgLcdOpenContext_onSoftbuttonsChanged_get(void * jarg1) {
  void * jresult ;
  lgLcdOpenContext *arg1 = (lgLcdOpenContext *) 0 ;
  lgLcdSoftbuttonsChangedContext *result = 0 ;
  
  arg1 = (lgLcdOpenContext *)jarg1; 
  result = (lgLcdSoftbuttonsChangedContext *)& ((arg1)->onSoftbuttonsChanged);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdOpenContext_device_set(void * jarg1, int jarg2) {
  lgLcdOpenContext *arg1 = (lgLcdOpenContext *) 0 ;
  int arg2 ;
  
  arg1 = (lgLcdOpenContext *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->device = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_lgLcdOpenContext_device_get(void * jarg1) {
  int jresult ;
  lgLcdOpenContext *arg1 = (lgLcdOpenContext *) 0 ;
  int result;
  
  arg1 = (lgLcdOpenContext *)jarg1; 
  result = (int) ((arg1)->device);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_lgLcdOpenContext() {
  void * jresult ;
  lgLcdOpenContext *result = 0 ;
  
  result = (lgLcdOpenContext *)calloc(1, sizeof(lgLcdOpenContext));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_lgLcdOpenContext(void * jarg1) {
  lgLcdOpenContext *arg1 = (lgLcdOpenContext *) 0 ;
  
  arg1 = (lgLcdOpenContext *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdOpenByTypeContext_connection_set(void * jarg1, int jarg2) {
  lgLcdOpenByTypeContext *arg1 = (lgLcdOpenByTypeContext *) 0 ;
  int arg2 ;
  
  arg1 = (lgLcdOpenByTypeContext *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->connection = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_lgLcdOpenByTypeContext_connection_get(void * jarg1) {
  int jresult ;
  lgLcdOpenByTypeContext *arg1 = (lgLcdOpenByTypeContext *) 0 ;
  int result;
  
  arg1 = (lgLcdOpenByTypeContext *)jarg1; 
  result = (int) ((arg1)->connection);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdOpenByTypeContext_deviceType_set(void * jarg1, int jarg2) {
  lgLcdOpenByTypeContext *arg1 = (lgLcdOpenByTypeContext *) 0 ;
  int arg2 ;
  
  arg1 = (lgLcdOpenByTypeContext *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->deviceType = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_lgLcdOpenByTypeContext_deviceType_get(void * jarg1) {
  int jresult ;
  lgLcdOpenByTypeContext *arg1 = (lgLcdOpenByTypeContext *) 0 ;
  int result;
  
  arg1 = (lgLcdOpenByTypeContext *)jarg1; 
  result = (int) ((arg1)->deviceType);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdOpenByTypeContext_onSoftbuttonsChanged_set(void * jarg1, void * jarg2) {
  lgLcdOpenByTypeContext *arg1 = (lgLcdOpenByTypeContext *) 0 ;
  lgLcdSoftbuttonsChangedContext *arg2 = (lgLcdSoftbuttonsChangedContext *) 0 ;
  
  arg1 = (lgLcdOpenByTypeContext *)jarg1; 
  arg2 = (lgLcdSoftbuttonsChangedContext *)jarg2; 
  if (arg1) (arg1)->onSoftbuttonsChanged = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_lgLcdOpenByTypeContext_onSoftbuttonsChanged_get(void * jarg1) {
  void * jresult ;
  lgLcdOpenByTypeContext *arg1 = (lgLcdOpenByTypeContext *) 0 ;
  lgLcdSoftbuttonsChangedContext *result = 0 ;
  
  arg1 = (lgLcdOpenByTypeContext *)jarg1; 
  result = (lgLcdSoftbuttonsChangedContext *)& ((arg1)->onSoftbuttonsChanged);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_lgLcdOpenByTypeContext_device_set(void * jarg1, int jarg2) {
  lgLcdOpenByTypeContext *arg1 = (lgLcdOpenByTypeContext *) 0 ;
  int arg2 ;
  
  arg1 = (lgLcdOpenByTypeContext *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->device = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_lgLcdOpenByTypeContext_device_get(void * jarg1) {
  int jresult ;
  lgLcdOpenByTypeContext *arg1 = (lgLcdOpenByTypeContext *) 0 ;
  int result;
  
  arg1 = (lgLcdOpenByTypeContext *)jarg1; 
  result = (int) ((arg1)->device);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_lgLcdOpenByTypeContext() {
  void * jresult ;
  lgLcdOpenByTypeContext *result = 0 ;
  
  result = (lgLcdOpenByTypeContext *)calloc(1, sizeof(lgLcdOpenByTypeContext));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_lgLcdOpenByTypeContext(void * jarg1) {
  lgLcdOpenByTypeContext *arg1 = (lgLcdOpenByTypeContext *) 0 ;
  
  arg1 = (lgLcdOpenByTypeContext *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdInit() {
  unsigned long jresult ;
  DWORD result;
  
  result = (DWORD)lgLcdInit();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdDeInit() {
  unsigned long jresult ;
  DWORD result;
  
  result = (DWORD)lgLcdDeInit();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdConnectW(void * jarg1) {
  unsigned long jresult ;
  lgLcdConnectContextW *arg1 = (lgLcdConnectContextW *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdConnectContextW *)jarg1; 
  result = (DWORD)lgLcdConnectW(arg1);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdConnectA(void * jarg1) {
  unsigned long jresult ;
  lgLcdConnectContextA *arg1 = (lgLcdConnectContextA *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdConnectContextA *)jarg1; 
  result = (DWORD)lgLcdConnectA(arg1);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdConnectExW(void * jarg1) {
  unsigned long jresult ;
  lgLcdConnectContextExW *arg1 = (lgLcdConnectContextExW *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdConnectContextExW *)jarg1; 
  result = (DWORD)lgLcdConnectExW(arg1);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdConnectExA(void * jarg1) {
  unsigned long jresult ;
  lgLcdConnectContextExA *arg1 = (lgLcdConnectContextExA *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdConnectContextExA *)jarg1; 
  result = (DWORD)lgLcdConnectExA(arg1);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdDisconnect(int jarg1) {
  unsigned long jresult ;
  int arg1 ;
  DWORD result;
  
  arg1 = (int)jarg1; 
  result = (DWORD)lgLcdDisconnect(arg1);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdSetDeviceFamiliesToUse(int jarg1, unsigned long jarg2, unsigned long jarg3) {
  unsigned long jresult ;
  int arg1 ;
  DWORD arg2 ;
  DWORD arg3 ;
  DWORD result;
  
  arg1 = (int)jarg1; 
  arg2 = (DWORD)jarg2; 
  arg3 = (DWORD)jarg3; 
  result = (DWORD)lgLcdSetDeviceFamiliesToUse(arg1,arg2,arg3);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdEnumerate(int jarg1, int jarg2, void * jarg3) {
  unsigned long jresult ;
  int arg1 ;
  int arg2 ;
  lgLcdDeviceDesc *arg3 = (lgLcdDeviceDesc *) 0 ;
  DWORD result;
  
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (lgLcdDeviceDesc *)jarg3; 
  result = (DWORD)lgLcdEnumerate(arg1,arg2,arg3);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdEnumerateExW(int jarg1, int jarg2, void * jarg3) {
  unsigned long jresult ;
  int arg1 ;
  int arg2 ;
  lgLcdDeviceDescExW *arg3 = (lgLcdDeviceDescExW *) 0 ;
  DWORD result;
  
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (lgLcdDeviceDescExW *)jarg3; 
  result = (DWORD)lgLcdEnumerateExW(arg1,arg2,arg3);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdEnumerateExA(int jarg1, int jarg2, void * jarg3) {
  unsigned long jresult ;
  int arg1 ;
  int arg2 ;
  lgLcdDeviceDescExA *arg3 = (lgLcdDeviceDescExA *) 0 ;
  DWORD result;
  
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (lgLcdDeviceDescExA *)jarg3; 
  result = (DWORD)lgLcdEnumerateExA(arg1,arg2,arg3);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdOpen(void * jarg1) {
  unsigned long jresult ;
  lgLcdOpenContext *arg1 = (lgLcdOpenContext *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdOpenContext *)jarg1; 
  result = (DWORD)lgLcdOpen(arg1);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdOpenByType(void * jarg1) {
  unsigned long jresult ;
  lgLcdOpenByTypeContext *arg1 = (lgLcdOpenByTypeContext *) 0 ;
  DWORD result;
  
  arg1 = (lgLcdOpenByTypeContext *)jarg1; 
  result = (DWORD)lgLcdOpenByType(arg1);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdClose(int jarg1) {
  unsigned long jresult ;
  int arg1 ;
  DWORD result;
  
  arg1 = (int)jarg1; 
  result = (DWORD)lgLcdClose(arg1);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdReadSoftButtons(int jarg1, void * jarg2) {
  unsigned long jresult ;
  int arg1 ;
  DWORD *arg2 = (DWORD *) 0 ;
  DWORD result;
  
  arg1 = (int)jarg1; 
  arg2 = (DWORD *)jarg2; 
  result = (DWORD)lgLcdReadSoftButtons(arg1,arg2);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdUpdateBitmap(int jarg1, void * jarg2, unsigned long jarg3) {
  unsigned long jresult ;
  int arg1 ;
  lgLcdBitmapHeader *arg2 = (lgLcdBitmapHeader *) 0 ;
  DWORD arg3 ;
  DWORD result;
  
  arg1 = (int)jarg1; 
  arg2 = (lgLcdBitmapHeader *)jarg2; 
  arg3 = (DWORD)jarg3; 
  result = (DWORD)lgLcdUpdateBitmap(arg1,(lgLcdBitmapHeader const *)arg2,arg3);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_lgLcdSetAsLCDForegroundApp(int jarg1, int jarg2) {
  unsigned long jresult ;
  int arg1 ;
  int arg2 ;
  DWORD result;
  
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = (DWORD)lgLcdSetAsLCDForegroundApp(arg1,arg2);
  jresult = (unsigned long)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

